# -- BASIC CONFIGURATION -- #

spring:
  application:
    name: discovery-server
  jmx:
    default-domain: ${spring.application.name}

# -- EUREKA CONFIGURATION -- #
eureka:
   client:
    # Since It is Discovery Server So we do not want this server to get self registered.
    register-with-eureka: false
    fetch-registry: false
   server:
     enable-self-preservation: false
server:
  port: 3421